services:
  postgres:
    image: postgres:17.5-alpine3.21
    container_name: honohub-issue-postgres
    ports:
      - 5432:5432
    volumes:
      - pgsdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
  app:
    build:
      context: .
      dockerfile: Express.Dockerfile
      # dockerfile: Dockerfile
    container_name: honohub-issue-app
    ports:
      - 80:3000

volumes:
  pgsdata:
